apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-model-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "34.144.233.78"  # Remplacez par le nom de votre IP statique
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Utilise Let's Encrypt via Cert-Manager
    networking.gke.io/managed-certificates: "managed-cert"  # Certificat managé par GKE
spec:
  rules:
    - host: "meta.bggn.ch"  # Remplacez par votre domaine
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - "meta.bggn.ch"
      secretName: letsencrypt-prod-tls  # Certificat généré automatiquement par Let's Encrypt
