apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-model-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Utilise Let's Encrypt via Cert-Manager
    networking.gke.io/managed-certificates: "managed-cert"  # Certificat managé par GKE
spec:
  rules:
    - host: "meta.bggn.ch"  # Remplacez par votre domaine
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: meta-model-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meta-model-frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - "meta.bggn.ch"
      secretName: letsencrypt-prod-tls  # Certificat généré automatiquement par Let's Encrypt
