name: CI/CD Pipeline with GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker du backend (Go)
      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-backend:latest -f ./backend/Dockerfile ./backend
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker du frontend (React)
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-frontend:latest

  build-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker de MongoDB avec init-phrases.js
      - name: Build and push MongoDB image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-mongodb:latest -f ./database/Dockerfile ./database
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-mongodb:latest

  deploy-to-gke:
    needs: [build-backend, build-frontend, build-database]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ajouter la clé GPG correcte pour le dépôt Google Cloud et installer gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update && sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin google-cloud-cli -y

      # Authentifier Google Cloud avec la clé JSON du compte de service
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          export_default_credentials: true
 
      # Configurer gcloud pour utiliser le projet Google Cloud et la zone
      - name: Set up Google Cloud configuration
        run: |
          gcloud config set compute/zone ${{ secrets.GKE_ZONE }}   

      # Obtenir les informations d'identification du cluster GKE
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }}

      - name: Deploy backend, frontend, MongoDB and services to GKE
        run: |
          kubectl apply -f kubernetes/namespace.yaml

      # Créer le secret Kubernetes pour le registre privé
      - name: Create Kubernetes secret for Docker registry (GHCR)
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username="${{ secrets.GHCR_USERNAME }}" \
            --docker-password="${{ secrets.GHCR_TOKEN }}" \
            --docker-email="${{ secrets.GHCR_EMAIL }}" \
            --dry-run=client -o yaml | kubectl apply -n meta-model -f -

      # Appliquer les fichiers Kubernetes pour déployer l'application
      - name: Deploy backend, frontend, MongoDB and services to GKE
        run: |
          kubectl apply -f kubernetes/mongodb-pvc.yaml
          kubectl apply -f kubernetes/mongodb-deployment.yaml
          kubectl apply -f kubernetes/mongodb-service.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml
          kubectl apply -f kubernetes/ingress.yaml