name: CI/CD Pipeline with GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker du backend (Go)
      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-backend:latest -f ./backend/Dockerfile ./backend
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker du frontend (React)
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-frontend:latest

  build-mongodb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker avec GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Construire l'image Docker de MongoDB avec init-phrases.js
      - name: Build and push MongoDB image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-mongodb:latest -f ./mongodb/Dockerfile ./mongodb
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/meta-model-mongodb:latest
